version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: idoctor_db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # nome do usuário
      MYSQL_USER: 'idoctor-root'
      # senha do usuário
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password1'
    expose: 
      - "3306"
    ports:
      # porta em que o banco estará rodando
      - "3306:3306"
    # volume do banco mapeado,espaço semelhante a um disco onde os dados serão salvos.
    volumes:
      - my-db:/var/lib/mysql
# nome do volume
volumes:
  my-db:
